version: '3.8'
services:
  backend:
    build: ./MyViewBackend
    ports:
      - "5000:80"
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
      - ASPNETCORE_URLS=http://+:80

  frontend:
    build: ./myview-frontend
    ports:
      - "3000:80"
    depends_on:
      - backend
